name: popular_movies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.0.1
  json_serializable: 6.3.1
  json_annotation: 4.6.0
  smartstruct: 1.2.6
  dartz: 0.10.1
  injectable: 1.5.3
  get_it: 7.2.0
  floor: 1.3.0
  retrofit: 3.0.1+1
  dio: 4.0.6
  freezed: 1.1.0
  cached_network_image: 3.2.1
  connectivity_plus: 2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.2.0
  injectable_generator: 1.5.2
  smartstruct_generator: 1.2.4+1
  floor_generator: 1.2.0
  retrofit_generator: 3.0.1+1

flutter:
  uses-material-design: true
