name: popular_movies
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.0.1
  json_serializable: 6.3.1
  json_annotation: 4.6.0
  smartstruct: 1.2.6
  dartz: 0.10.1
  injectable: 1.5.3
  get_it: 7.2.0
  floor: 1.3.0
  sqflite: 2.0.3
  retrofit: 3.0.1+1
  dio: 4.0.6
  cached_network_image: 3.2.1
  connectivity_plus: 2.3.6
  freezed_annotation: 1.1.0
  faker: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer: '>=2.1.0 <5.0.0'
  build_runner:
  freezed:
  mockito: 5.0.17
  injectable_generator:
  smartstruct_generator:
  floor_generator:
  retrofit_generator:

flutter:
  uses-material-design: true
